name: new tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - class-actions


jobs:
  build:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip and install dependencies
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install pipx
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath

      - name: Install Ruff
        run: pipx install ruff

      - name: Lint code with Ruff
        run: ruff check --output-format=github --target-version=py39 .

      - name: Check code formatting with Ruff
        run: ruff format --diff --target-version=py39 .
        continue-on-error: true
      - name: Run script
        run: ./joke.sh

       
